version: '3.7'

networks:
  react:

services:

  react-frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
      - ./certs:/etc/nginx/certs
    ports:
      - '80:80'
      - '443:443'

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - .:/var/www/html
    ports:
      - 3002:3000
      - 3003:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - react